name: Setup Node.js Environment
description: Checks out code, caches node_modules and installs dependencies
inputs:
    node-version:
        description: The version of Node.js to use
        required: true
        default: '16'

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}

        - name: Cache node modules
          id: npm-cache
          env:
              cache-name: node-modules-cache
          uses: actions/cache@v3
          with:
              path: |
                  ~/.npm
              key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          run: npm install
          shell: bash
