name: Setup Node.js Environment
description: Checks out code, caches node_modules and installs dependencies
inputs:
  node-version:
    description: The version of Node.js to use
    required: true
    default: '14'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules
      env:
        cache-name: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install