version = 0.1
[default.deploy.parameters]
stack_name = "serverless-api"
resolve_s3 = true
s3_prefix = "serverless-api"
region = "ca-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
