org: pabdelli
app: serverless-api
# serverless.yml

service: serverless-api
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: 'ca-central-1'
    profile: 'default'

functions:
    api:
        handler: src/index.handler
        events:
            - httpApi: '*'

plugins:
    - serverless-plugin-typescript
    - serverless-offline
