AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Parameters: # Added this section
    ApiUrl:
        Description: The STM API URL
        Type: String
    ApiKey:
        Description: The STM API Key
        Type: String

Globals:
    Function:
        Timeout: 600

Resources:
    ExpressApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            BinaryMediaTypes: ['*/*']

    ExpressFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: dist/index.handler
            Runtime: nodejs14.x
            MemorySize: 512
            Environment:
                Variables:
                    API_URL: !Ref ApiUrl
                    API_KEY: !Ref ApiKey
            Events:
                ExpressFunctionProxy:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ExpressApi
                        Path: '/{proxy+}'
                        Method: ANY
                ExpressFunctionRoot:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ExpressApi
                        Path: '/'
                        Method: ANY

Outputs:
    ExpressFunctiondApi:
        Description: 'API Gateway endpoint URL for Prod stage for Express function'
        Value: !Sub 'https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
    ExpressFunction:
        Description: 'Express Lambda Function ARN'
        Value: !GetAtt ExpressFunction.Arn
    ExpressFunctionIamRole:
        Description: 'Implicit IAM Role created for Express function'
        Value: !GetAtt ExpressFunctionRole.Arn
