name: Run tests 
description: Run Jest tests and deploy test coverage to github pages
inputs:
  node-version: 
    description: The version of Node.js to use
    required: true
    default: '14'

runs:
  using: composite
  steps: 
    - name: Run tests
      env:
        API_URL: mockURL
        API_KEY: mockKey
      run: npm run test 
      shell: bash