name: Run tests 
description: Run Jest tests 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: ./.github/actions/setup-node

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: npm test