name: ESLint

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Check out code
          uses: actions/checkout@v2                            

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
            
        - name: Install dependencies
          run: npm install
            
        - name: Lint with ESLint and auto fix
          # Lint all JavaScript files using config file and fix any errors 
          run: npx eslint --config .eslintrc.yml --ext .js --fix ./src
        
        - name: Commit fixes if needed
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            if [[ $(git diff --stat './src/**/*.js') != '' ]]; then 
                git add ./src/**/*.js
                git diff --stat -- './src/**/*.js'
                git commit -m "Fix lint errors on JS files"

                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@https://github.com/Monitoring-Mtl/Serverless-API.git
                git push origin ${GITHUB_REF#refs/heads/}
            else
                echo "No lint errors found"
            fi
        
        
            