name: Linting

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
      
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup runner
          uses: ./.github/actions/setup-node

        - name: Lint with ESLint and auto fix
          # Lint all JavaScript and Typescript files using config file and fix any errors 
          run: |
            npm run lint --fix
            npm run format
        
        - name: Commit fixes if needed
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            if [[ $(git diff --stat) != '' ]]; then 
                git commit -am "Fix lint errors"
            else
                echo "No lint errors found"
            fi
        
        
            