name: Continuous Deployment

on: 
    push:
        branches:
        - master
    # Allows the manual execution of the workflow from the Action tab
    workflow_dispatch:
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write

# Allow one concurrent deployment
concurrency:
   group: 'pages'
   cancel-in-progress: true

jobs: 

    lint-and-test:
      name: Lint, test and deploy test coverage to Github Pages 
      uses: ./.github/workflows/lint-test-workflow.yml
      with:
        deploy-test-coverage: true

    
    deploy:
      name: Deploy to AWS
      needs: [lint-and-test]
      runs-on: ubuntu-latest

      steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred AWS region

      - name: Build and Deploy to AWS
        run: npm run deploy
