name: Continuous Deployment

on: 
    push:
        branches:
        - master
    # Allows the manual execution of the workflow from the Action tab
    workflow_dispatch:

jobs: 

    lint-and-test:
      name: Lint, test and deploy test coverage to Github Pages 
      uses: ./.github/workflows/lint-test-workflow.yml
      with:
        deploy-test-coverage: true

    
    deploy:
      name: Deploy to AWS
      needs: [lint-and-test]
      runs-on: ubuntu-latest

      steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      
      - name: Build and Deploy to AWS
        run: npm run deploy
