name: Continuous Integration

on:
  pull_request:
    branches:
        - master

  # Allows the manual execution of the workflow from the Action tab
  workflow_dispatch:

jobs:

    lint-and-test:
      uses: ./.github/workflows/reusable/lint-test-workflow.yml



      
