name: Continuous Integration

on:
  pull_request:
    branches:
        - master

  # Allows the manual execution of the workflow from the Action tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write

# Allow one concurrent deployment
concurrency:
   group: 'pages'
   cancel-in-progress: true

jobs:

    linting:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup runner
        uses: ./.github/actions/setup-node

      - name: Lint with ESLint and auto fix
        # Lint all JavaScript and Typescript files using config file and fix any errors 
        run: |
          npm run lint --fix
          npm run format
      
      - name: Commit fixes if needed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [[ $(git diff --stat) != '' ]]; then 
              git commit -am "Fix lint errors"
          else
              echo "No lint errors found"
          fi

    testing:

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}/coverage

      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup runner
        uses: ./.github/actions/setup-node

      - name: Run tests
        env:
          API_URL: mockURL
          API_KEY: mockKey
        run: npm run test 
        continue-on-error: true
      
      - name: Configure pages
        uses: actions/configure-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./coverage/lcov-report
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: test-results
